import pandas as pd
csv_path = "data/csi300_daily.csv"
df = pd.read_csv(csv_path, encoding="utf-8-sig",parse_dates=["date"])
df["date"] = pd.to_datetime(df["date"])
print("对象类型: ")
print(type(df))
print("\n数据规模: ")
print(df.shape)
print("\n列信息: ")
print(df.columns)
print("\n各列数据类型: ")
print(df.dtypes)
print("\n行索引 :")
print(df.index)
print("\n前五行数据: ")
print(df.head())
print("\n后五行数据: ")
print(df.tail())
print("\n缺失值统计: ")
print(df.isna().sum())
print("\n描述性统计: ")
print(df.describe())
print("\n最早日期: ")
print(df["date"].min())
print("\n最晚日期: ")
print(df["date"].max())